<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use App\Models\DocumentRequest;

class DocumentRequestStatusUpdated extends Notification
{
    use Queueable;

    public DocumentRequest $docRequest;

    public function __construct(DocumentRequest $docRequest)
    {
        $this->docRequest = $docRequest;
    }

    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $docType = ucwords(str_replace('_', ' ', $this->docRequest->document_type));
        $status  = $this->docRequest->status;
        $name    = trim(($notifiable->first_name ?? '') . ' ' . ($notifiable->last_name ?? ''));

        // Subject & emoji per status
        $subjects = [
            'processing' => 'Document Being Processed — Barangay San Miguel II 🔄',
            'ready'      => 'Document Ready for Pick-up — Barangay San Miguel II ✅',
            'released'   => 'Document Released — Barangay San Miguel II ✅',
        ];
        $subject = $subjects[$status] ?? '📋 Document Status Update — Barangay San Miguel II';

        // Status-specific message
        $messages = [
            'processing' => 'We would like to inform you that your document request is now being processed by our office. We will notify you again once it is ready for pick-up.',
            'ready'      => 'Your document is READY for pick-up! Please visit the Barangay Hall during office hours (Mon–Fri, 8AM–5PM) to claim your ' . $docType . '.',
            'released'   => 'Your ' . $docType . ' has been successfully released. Thank you for availing our barangay services.',
        ];
        $message = $messages[$status] ?? 'The status of your document request has been updated.';

        $mail = (new MailMessage)
            ->subject($subject)
            ->from(config('mail.from.address'), 'Barangay San Miguel II — Official')
            ->greeting('Dear ' . ($name ?: 'Resident') . ',')
            ->line($message)
            ->line('---')
            ->line('**Document:** ' . $docType)
            ->line('**Status:** ' . ucfirst($status));

        if ($status === 'ready') {
            $mail->line('---')
                 ->line('📍 **Location:** Barangay San Miguel II Hall, Dasmariñas City, Cavite')
                 ->line('🕐 **Office Hours:** Monday to Friday, 8:00 AM – 5:00 PM')
                 ->line('Please bring a valid ID when claiming your document.');
        }

        if ($status === 'released') {
            $mail->line('---')
                 ->line('If you have any concerns regarding your document, please visit the Barangay Hall or contact us through our official channels.');
        }

        return $mail
            ->action('View My Requests', url('/resident'))
            ->salutation(
                '— Barangay San Miguel II' . "\n" .
                'Dasmariñas City, Cavite' . "\n\n" .
                '*This is an automated message generated by the Barangay San Miguel II Management System. ' .
                'Please do not reply to this email. For inquiries, please visit the barangay hall in person ' .
                'or contact us through our official Facebook page.*'
            );
    }

    public function toArray(object $notifiable): array
    {
        $docType = ucwords(str_replace('_', ' ', $this->docRequest->document_type));
        $status  = $this->docRequest->status;

        $titles = [
            'processing' => 'Document Being Processed 🔄',
            'ready'      => 'Ready for Pick-up! ✅',
            'released'   => 'Document Released 📦',
        ];

        $messages = [
            'processing' => 'Your ' . $docType . ' is now being processed. We will notify you when it\'s ready.',
            'ready'      => 'Your ' . $docType . ' is ready! Please visit Barangay Hall (Mon–Fri, 8AM–5PM) to claim it.',
            'released'   => 'Your ' . $docType . ' has been released. Thank you!',
        ];

        return [
            'type'    => 'document_status_updated',
            'title'   => $titles[$status]  ?? 'Document Status Updated📋 ',
            'message' => $messages[$status] ?? 'Your document request status has been updated to: ' . ucfirst($status),
        ];
    }
}
