<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use App\Models\DocumentRequest;

class DocumentRequestStatusUpdated extends Notification
{
    use Queueable;

    public DocumentRequest $docRequest;

    public function __construct(DocumentRequest $docRequest)
    {
        $this->docRequest = $docRequest;
    }

    public function via(object $notifiable): array
    {
        if ($this->docRequest->status === 'released') {
            return ['mail'];
        }
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $docType = ucwords(str_replace('_', ' ', $this->docRequest->document_type));
        $status  = $this->docRequest->status;
        $name    = trim(($notifiable->first_name ?? '') . ' ' . ($notifiable->last_name ?? ''));

        // Subject & emoji per status
        $subjects = [
            'processing' => 'Document Being Processed — Barangay San Miguel II 🔄',
            'ready'      => 'Document Ready for Pick-up — Barangay San Miguel II ✅',
            'released'   => 'Document Released — Barangay San Miguel II ✅',
            'disapproved' => 'Document Request Disapproved — Barangay San Miguel II ❌',
        ];
        $subject = $subjects[$status] ?? '📋 Document Status Update — Barangay San Miguel II';

        // Status-specific message
        $messages = [
            'processing' => 'We would like to inform you that your document request is now being processed by our office. We will notify you again once it is ready for pick-up.',
            'ready'      => 'Your document is READY for pick-up! Please visit the Barangay Hall during office hours (Mon–Fri, 8AM–5PM) to claim your ' . $docType . '.',
            'released'   => 'Your ' . $docType . ' has been successfully released. Thank you for availing our barangay services.',
            'disapproved' => 'We regret to inform you that your document request has been DISAPPROVED by our office.',
        ];
        $message = $messages[$status] ?? 'The status of your document request has been updated.';

        $mail = (new MailMessage)
            ->subject($subject)
            ->from(config('mail.from.address'), 'Barangay San Miguel II — Official')
            ->greeting('Dear ' . ($name ?: 'Resident') . ',')
            ->line($message)
            ->line('---')
            ->line('**Document:** ' . $docType)
            ->line('**Status:** ' . ucfirst($status));

        if ($status === 'ready') {
            $mail->line('---')
                 ->line('📍 **Pick-up Schedule:**')
                 ->line('📅 **Date:** ' . ($this->docRequest->pickup_date ? \Carbon\Carbon::parse($this->docRequest->pickup_date)->format('F d, Y') : 'Please visit during office hours'))
                 ->line('🕐 **Time:** ' . ($this->docRequest->pickup_time ? \Carbon\Carbon::parse($this->docRequest->pickup_time)->format('h:i A') : '8:00 AM – 5:00 PM'))
                 ->line('👤 **Personnel in Charge:** ' . ($this->docRequest->personnel_in_charge ?: 'Duty Officer'))
                 ->line('👥 **Alternate Personnel:** ' . ($this->docRequest->alternate_personnel ?: 'Any available staff (Barangay San Miguel II Hall, Dasmariñas City, Cavite)'))
                 ->line('📍 **Location:** Barangay San Miguel II Hall, Dasmariñas City, Cavite')
                 ->line('---')
                 ->line('Please bring a valid ID when claiming your document.');
        }

        if ($status === 'released') {
            $mail->line('---')
                 ->line('If you have any concerns regarding your document, please visit the Barangay Hall or contact us through our official channels.');
        }
        
        if ($status === 'disapproved') {
            $mail->line('---')
                 ->line('**Reason for Disapproval:**')
                 ->line($this->docRequest->disapproval_reason ?: 'No specific reason provided.')
                 ->line('---')
                 ->line('If you believe this is an error, please visit the Barangay Hall with the required documents.');
        }

        return $mail
            ->action('View My Requests', url('/resident'))
            ->salutation(
                '— Barangay San Miguel II' . "\n" .
                'Dasmariñas City, Cavite' . "\n\n" .
                '*This is an automated message generated by the Barangay San Miguel II Management System. ' .
                'Please do not reply to this email. For inquiries, please visit the barangay hall in person ' .
                'or contact us through our official Facebook page.*'
            );
    }

    public function toArray(object $notifiable): array
    {
        $docType = ucwords(str_replace('_', ' ', $this->docRequest->document_type));
        $status  = $this->docRequest->status;

        $titles = [
            'processing' => 'Document Being Processed 🔄',
            'ready'      => 'Ready for Pick-up! ✅',
            'released'   => 'Document Released 📦',
            'disapproved' => 'Request Disapproved ❌',
        ];

        $messages = [
            'processing' => 'Your ' . $docType . ' is now being processed. We will notify you when it\'s ready.',
            'ready'      => 'Your ' . $docType . ' is ready! ' .
                            ($this->docRequest->pickup_date ? 'Date: ' . \Carbon\Carbon::parse($this->docRequest->pickup_date)->format('M d, Y') . '. ' : '') .
                            ($this->docRequest->pickup_time ? 'Time: ' . \Carbon\Carbon::parse($this->docRequest->pickup_time)->format('h:i A') . '. ' : '') .
                            ($this->docRequest->personnel_in_charge ? 'Look for: ' . $this->docRequest->personnel_in_charge . '. ' : '') .
                            ($this->docRequest->alternate_personnel ? 'Alternate: ' . $this->docRequest->alternate_personnel . '. ' : ''),
            'released'   => 'Your ' . $docType . ' has been released. Thank you!',
            'disapproved' => 'Your ' . $docType . ' request was disapproved. ' . ($this->docRequest->disapproval_reason ? 'Reason: ' . $this->docRequest->disapproval_reason : ''),
        ];

        return [
            'type'    => 'document_status_updated',
            'document_request_id' => $this->docRequest->id,
            'status'  => $status,
            'title'   => $titles[$status]  ?? 'Document Status Updated📋 ',
            'message' => $messages[$status] ?? 'Your document request status has been updated to: ' . ucfirst($status),
        ];
    }
}
