<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('digital_ids', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            $table->string('contact_person');
            $table->string('contact_person_number');
            $table->enum('status', ['pending', 'generated'])->default('pending');
            $table->string('id_number')->nullable(); // generated by office
            $table->timestamps();
        });
    }

    public function down(): void {
        Schema::dropIfExists('digital_ids');
    }
};
